#
# R program file plot4.R
#
# Data file "household_power_consumption_cleaned.txt",
# as generated by Cleaning_HPC.R
# must be located in the same directory
#
# This program reads
#   "household_power_consumption_cleaned.txt"
# and produces the 4th plot
#
# read...
hpc<-read.csv("household_power_consumption_cleaned.txt",stringsAsFactors = FALSE)
hpc$datetime <- strptime(hpc$datetime,"%Y-%m-%d %T")    ## date needs to be converted to POSIXlt
# ... draw

with (hpc, {
      par(mfrow = c(2, 2), mar = c(5, 5, 2, 2), oma = c(0, 0.5, 1, 1), cex.lab = 0.9)
      plot(datetime,Global_active_power,type="l",ylab = "Global Active Power", xlab ="")
      plot(datetime,Voltage, type="l",ylab = "Voltage")
      
      plot(datetime,Sub_metering_1,type = "n", ylab = "Energy sub metering", xlab ="")
      lines(datetime,Sub_metering_1, col = "black")
      lines(datetime,Sub_metering_2, col = "red")
      lines(datetime,Sub_metering_3, col = "blue")
      legend("topright", lty = 1, col = c("black", "red", "blue"), 
             legend = sapply(colnames(hpc)[6:8], function(x) paste(x," ")),cex=0.7, bty="n")
      
      plot(datetime,Global_reactive_power, type="l", cex.axis = 0.9)
      
      }
)
# ... copy to file
dev.copy(png, file = "plot4.png", width=480, height=480) ## 480 is the default anyway
# close it
dev.off()












