#
# R program file plot1.R
#
# Data file "household_power_consumption_cleaned.txt",
# as generated by Cleaning_HPC.R
# must be located in the same directory
#
# This program reads
#   "household_power_consumption_cleaned.txt"
# and produces the 1st plot
#
# read...
hpc<-read.csv("household_power_consumption_cleaned.txt", stringsAsFactors = FALSE)
hpc$datetime <- strptime(hpc$datetime,"%Y-%m-%d %T")                ## date needs to be converted to POSIXlt
# ... draw
par(mfrow = c(1,1), oma = c(0, 0.5, 1, 1))
hist(hpc$Global_active_power, xlab = "Global ActivePower (kilowatts)", 
     main = "Global Active Power", col ="red")
# ... copy to file
dev.copy(png, file = "plot1.png", width=480, height=480) ## 480 is the default anyway
# close it
dev.off()
