#
# R program file plot3.R
#
# Data file "household_power_consumption_cleaned.txt",
# as generated by Cleaning_HPC.R,
# must be located in the same directory
#
# This program reads
#   "household_power_consumption_cleaned.txt"
# and produces the 3rd plot
#
# read...
hpc<-read.csv("household_power_consumption_cleaned.txt",stringsAsFactors = FALSE)
hpc$datetime <- strptime(hpc$datetime,"%Y-%m-%d %T")    ## date needs to be converted to POSIXlt
# ... draw
par(mfrow = c(1,1), oma = c(0, 0.5, 1, 0))
plot(hpc$datetime,hpc$Sub_metering_1,type = "n", ylab = "Energy sub metering", xlab ="")
lines(hpc$datetime,hpc$Sub_metering_1, col = "black")
lines(hpc$datetime,hpc$Sub_metering_2, col = "red")
lines(hpc$datetime,hpc$Sub_metering_3, col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), 
       legend = sapply(colnames(hpc)[6:8], function(x) paste(x," ")), cex=0.8)
# ... copy to file
dev.copy(png, file = "plot3.png") ## 480 is the default anyway
# close it
dev.off()











